<?php

return [
    'DB'        => 'SilexStarter\StaticProxy\Database',
    'Dispatcher'=> 'SilexStarter\StaticProxy\Dispatcher',
    'Event'     => 'SilexStarter\StaticProxy\Event',
    'Url'       => 'SilexStarter\StaticProxy\Url',
    'App'       => 'SilexStarter\StaticProxy\Application',
    'File'      => 'SilexStarter\StaticProxy\Filesystem',
    'View'      => 'SilexStarter\StaticProxy\View',
    'Menu'      => 'SilexStarter\StaticProxy\Menu',
    'Route'     => 'SilexStarter\StaticProxy\Router',
    'Session'   => 'SilexStarter\StaticProxy\Session',
    'Request'   => 'SilexStarter\StaticProxy\Request',
    'Response'  => 'SilexStarter\StaticProxy\Response',
    'Config'    => 'SilexStarter\StaticProxy\Config',
    'Module'    => 'SilexStarter\StaticProxy\Module',
    'Asset'     => 'SilexStarter\StaticProxy\Asset',
    'Sentry'    => 'SilexStarter\StaticProxy\Sentry',
    'Str'       => 'Illuminate\Support\Str',
    'Model'     => 'Illuminate\Database\Eloquent\Model',
    'Controller'=> 'SilexStarter\Controller\Controller',
    'ContainerAwareController'  => 'SilexStarter\Controller\ContainerAwareController',
    'DispatcherAwareController' => 'SilexStarter\Controller\DispatcherAwareController',
];
